package com.example.taptimingkeyboard.keyboard;

/**
 * The button of {@link TapTimingKeyboard}
 */
public class TTKeyboardButton extends TTKeyboardElement {

    private String label;
    private int code;
    //proportion of standard button size
    private float size=1.0f;

    /**
     * Instantiates a new TTKeyboardButton with standard size (1.0)
     *
     * @param label
     * @param code
     */
    TTKeyboardButton(String label, int code) {
        this.label = label;
        this.code = code;
    }

    /**
     * Instantiates a new TTKeyboardButton
     * @param label
     * @param code
     * @param size
     */
    TTKeyboardButton(String label, int code, float size) {
        this.label = label;
        this.code = code;
        this.size = size;
    }

    /**
     * Instantiates a new TTKeyboardButton with standard size (1.0)
     *
     * @param label The label of the button and character generated by the button.
     */
    TTKeyboardButton(char label) {
        this.label = ""+label;
        this.code = label;
    }

    /**
     * @return The label - a text which will be used as the button label.
     */
    public String getLabel() {
        return label;
    }

    /**
     * @return The code of the character which the button generates.
     */
    public int getCode() {
        return code;
    }

    /**
     * @return The horizontal size of the button. The proportion of the sum of the sizes of all the elements in {@link TTKeyboardRow}
     */
    public float getSize() {
        return size;
    }

    @Override
    public int hashCode() {
        return (label+code+size).hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        return (obj instanceof TTKeyboardButton)
                && ((TTKeyboardButton)obj).getLabel().equals(label)
                && ((TTKeyboardButton)obj).getCode()==code
                && ((TTKeyboardButton)obj).getSize()==size;
    }
}
