package com.example.taptimingkeyboard.data;

import androidx.annotation.Nullable;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

/**
 * Stores information about test session.
 */
@Entity (tableName = "test_sessions")
public class TestSession {

    @PrimaryKey(autoGenerate = true)
    private long id;
    private long userId;
    private long timestampMs;
    @Nullable
    private long sessionEndTimestampMs;
    private String wordlistName;
    private String wordlistWordsMd5Hash;
    @Nullable
    private int numErrors;
    @Nullable
    private Boolean isOrientationLandscape;
    private String phoneInfo;
    private float phoneXDpi;
    private float phoneYDpi;

    /**
     * Creates instance with data that could be determined on the beginning of the test session
     *
     * @param userId                 see {@link #getUserId()}
     * @param timestampMs            see {@link #getTimestampMs()}
     * @param wordlistName           see {@link #getWordlistName()}
     * @param wordlistWordsMd5Hash   see {@link #getWordlistWordsMd5Hash()}
     * @param isOrientationLandscape see {@link #getOrientationLandscape()}
     * @param phoneInfo              see {@link #getPhoneInfo()}
     * @param phoneXDpi              see {@link #getPhoneXDpi()}
     * @param phoneYDpi              see {@link #getPhoneYDpi()}
     */
    public TestSession(long userId, long timestampMs, String wordlistName, String wordlistWordsMd5Hash, @Nullable Boolean isOrientationLandscape, String phoneInfo, float phoneXDpi, float phoneYDpi) {
        this.userId = userId;
        this.timestampMs = timestampMs;
        this.wordlistName = wordlistName;
        this.wordlistWordsMd5Hash = wordlistWordsMd5Hash;
        this.isOrientationLandscape = isOrientationLandscape;
        this.phoneInfo = phoneInfo;
        this.phoneXDpi = phoneXDpi;
        this.phoneYDpi = phoneYDpi;
    }

    /**
     * Sets id.
     *
     * @param id see {@link #getId()}
     */
    public void setId(long id) {
        this.id = id;
    }

    /**
     * Gets id.
     *
     * @return The unique id (auto generated by Room Library)
     */
    public long getId() {
        return id;
    }

    /**
     * Gets userId.
     *
     * @return Id of the user for this test session, determined by test session activity.
     */
    public long getUserId() {
        return userId;
    }

    /**
     * Gets timestampMs.
     *
     * @return The timestamp of the beginning of the session in milliseconds.
     */
    public long getTimestampMs() {
        return timestampMs;
    }

    /**
     * Gets sessionEndTimestampMs.
     *
     * @return The timestamp of the ending of the session in milliseconds.
     */
    public long getSessionEndTimestampMs() {
        return sessionEndTimestampMs;
    }

    /**
     * Gets wordlistName.
     *
     * @return The name of the word list used in test session.
     */
    public String getWordlistName() {
        return wordlistName;
    }

    /**
     * Gets wordlistWordsMd5Hash.
     *
     * @return The md5 hash of comma separated (no spaces), lower case words used in test session.
     */
    public String getWordlistWordsMd5Hash() {
        return wordlistWordsMd5Hash;
    }

    /**
     * Gets numErrors.
     *
     * @return The number of errors (when typing specified word) in this session.
     */
    public int getNumErrors() {
        return numErrors;
    }

    /**
     * Gets orientationLandscape.
     *
     * @return True - test session was in landscape screen orientation, false - portrait orientation.
     */
    @Nullable
    public Boolean getOrientationLandscape() {
        return isOrientationLandscape;
    }

    /**
     * Gets phoneInfo.
     *
     * @return Device info. The string: Build.BRAND+","+Build.MODEL+","+Build.PRODUCT+","+Build.DEVICE
     */
    public String getPhoneInfo() {
        return phoneInfo;
    }

    /**
     * Gets phoneXDpi.
     *
     * @return Dpi of the device's screen in x dimension.
     */
    public float getPhoneXDpi() {
        return phoneXDpi;
    }

    /**
     * Gets phoneYDpi.
     *
     * @return Dpi of the device's screen in y dimension.
     */
    public float getPhoneYDpi() {
        return phoneYDpi;
    }

    /**
     * Sets sessionEndTimestampMs.
     *
     * @param sessionEndTimestampMs see {@link #getSessionEndTimestampMs()}
     */
    public void setSessionEndTimestampMs(long sessionEndTimestampMs) {
        this.sessionEndTimestampMs = sessionEndTimestampMs;
    }

    /**
     * Sets numErrors.
     *
     * @param numErrors see {@link #getNumErrors()}
     */
    public void setNumErrors(int numErrors) {
        this.numErrors = numErrors;
    }
}
